language: python

python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"
    - "3.4"

matrix:
    allow_failures:
        - python: "3.2"
        - python: "3.3"
        - python: "3.4"
        - python: "pypy"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip install unittest2; fi
    - pip install future
    - python setup.py install --quiet
    - pip install --quiet pytest-cov

script:
    - nosetests --ignore-files=test_examples --with-coverage --cover-package=pattern
    - nosetests test/test_examples.py --with-coverage --cover-package=pattern

after_success:
    - pip install --quiet coveralls
    - coveralls
